version: 6.1.0.{build}
configuration: Release
platform: All
build:
  project: lowcdc/lowcdc.proj
  verbosity: minimal
artifacts:
- path: "*.zip"

after_build:
- ps: .\.appveyor\appveyor.after-build.ps1
